Add UP and DOWN keys to scroll past commands
AY2324S2-CS2103T-T11-2/tp pull request #102
Opened 2024-03-31 15:18 UTC by ChillinRage

Closes #77 

Didn't use `ListIterator` since pressing up and down repeatedly will not change the command shown (due to how they implement `next` and` previous`), but it should toggle between 2 commands.

2024-03-31 15:28 UTC, ChillinRage commented
I tried implementing test case for `commandBox`, but seems like I can't get `commandBox` itself to be displayed (unlike `helpWindow`).

Every method is set to private, and is called through the GUI.
`commandTextField.requestFocus()` then `robot.press(...)` wouldn't work either since the box is not a window.

2024-03-31 19:57 UTC, E0735389 requested changes
For testing this, a relatively simple way is to factor out the logic part into a `CommandHistoryModel`, which contains

* `addExecutedCommand(String command)`
* `String getPreviousCommandHistory()`
* `String getNextCommandHistory()`

and test only that. Of course the GUI is still untested but I suppose it's fine.

Design-wise, this also somewhat makes sense (later on you may want to write a web-based GUI or a terminal user interface using the same model? Why duplicate the code? There's nothing inherently JavaFX with the model)

Also, `bash` has this feature: assume you type a part of the current command `abc`, the previous command is `def`, you (accidentally) press `[↑]`, the command-line changes to `def`, then you press `[↓]`, the command should change **back** to `abc`.

Usability-wise, this makes sense (if the user accidentally press `[↑]`, there should be an easy way to undo it instead of making the user re-type the command again)



This also applies when the user is editing a **past** command and accidentally press `[↑]`.

Apart from that point, we need not imitate bash's behavior completely. (bash also has the feature that if you edit some past command, the edit *persists* across executions, this is not too important in my opinion)

2024-04-02 04:15 UTC, ChillinRage commented
A bit of things I want to clarify.
Suppose that the current simplified history is `add`, `edit 1`, `delete 4`.
- User types `hel`, then press UP. > now showing `delete 4`
- User edits it to `delete 2` then press UP again. > now showing `edit 1`
- User edits it to `edit` then press DOWN. > now showing `delete 2`
- User press DOWN again, > now showing `hel`
- User edits it to `help` and enter.
- Now the history is back to `add`, `edit 1`, `delete 4`, `help`. 

Is that the gist of it? (In regards to what you're suggesting?)

I'll omit the "edit persists across executions" because in windows, pressing up and down will not save the current changes (i.e. current behavior of this `commandHistory`).

2024-04-02 06:06 UTC, E0735389 commented
Sounds good to me.

2024-04-03 03:43 UTC, E0735389 reviewed
Just minor typo but not that important. These are easy to fix quickly anyway.

2024-04-03 03:43 UTC, E0735389 commented on src/main/java/seedu/address/model/CommandHistoryModel.java
> +     * Replaces the current command with {@code currenText} and returns the next newest command in the command history.
Typo "currenText"

2024-04-03 03:43 UTC, E0735389 commented on src/main/java/seedu/address/model/CommandHistoryModel.java
> +    public String getNextCommandHistory(String currrentText) {
Typo "currrentText"

2024-04-03 03:43 UTC, E0735389 commented on src/main/java/seedu/address/model/CommandHistoryModel.java
> +     * Replaces the current command with {@code currenText} and returns the next oldest command in the command history.
Same typo as above (twice)

2024-04-03 03:43 UTC, E0735389 commented on src/main/resources/view/CommandBox.fxml
> +<StackPane styleClass="stack-pane" xmlns="http://javafx.com/javafx/21" xmlns:fx="http://javafx.com/fxml/1">
You're using different version of JavaFX? (Doesn't sound like a good idea to have incompatible versions...?)

2024-04-03 04:01 UTC, ChillinRage commented
Sorry I didn't pull the newer changes.

2024-04-03 04:08 UTC, ChillinRage commented
I'm not sure if I should add the `requireNonNull(command)` line at CommandHistoryModel line 34 since practically, it's not possible for commandBox to ever call `addCommand` with a null parameter.

2024-04-03 04:55 UTC, E0735389 commented
Just apply defensive coding in general. The only disadvantage I can think of is to make code larger (marginally, doesn't matter that much) and slow down execution (also marginally, doesn't matter that much)

2024-04-03 08:04 UTC, merged