Add Course tag to person
AY2324S2-CS2103T-T11-2/tp pull request #32
Opened 2024-03-16 12:43 UTC by ChillinRage

Add Course class to person package.

Modify parser to check for mandatory course tag for add and edit commands

Main window now also display contacts' course code.

2024-03-17 12:51 UTC, E0735389 commented
Consider fixing the trailing spaces issues (as reported by the failing tests).

2024-03-19 17:10 UTC, ChillinRage commented
Role isn't included in the test files, I'll work on it.

2024-03-20 03:18 UTC, E0735389 requested changes

2024-03-20 03:18 UTC, E0735389 commented on src/main/java/seedu/address/logic/commands/AddCommand.java
> +            + PREFIX_COURSE + "CS2103T"
Try running the command `add` without any argument (which is invalid). You'll see the error message being

```
Example: add n/John Doe p/98765432 e/johnd@example.com r/STUDENT a/311, Clementi Ave 2, #02-25 c/CS2103Tt/friends t/owesMoney
                                                                                                       ^^
```

There's an obvious missing space pointed out there.

2024-03-20 14:38 UTC, closed without merging