Edit find to enable finding people by course code
AY2324S2-CS2103T-T11-2/tp pull request #95
Opened 2024-03-30 16:28 UTC by Hibeom0929

Pass all the words from the input to both NameContainsKeywordPredict and CourseContainsKeywordPredict.
Possible improvement:
- if Name reads a word as name, Course will not read that word again.
- For now, the person is detected when the full word matches any word in the name or course. ex) find Alic will not list Alice, find cs2103 will not list cs2103T. I think it is fine for the name but for the course code, not sure if approving short cut is better or not.

2024-03-31 01:57 UTC, E0735389 requested changes
Apart from these minor changes pointed out, overall there appears to be some unnecessary duplication of logic in `NameContainsKeywordPredicate` and `CourseContainsKeywordPredicate`. How does the rest think about the design?

2024-03-31 01:57 UTC, E0735389 commented on src/main/java/seedu/address/logic/parser/FindCommandParser.java
> +        String[] Keywords = trimmedArgs.split("\\s+");
This violates the naming convention

2024-03-31 01:57 UTC, E0735389 commented on src/main/java/seedu/address/logic/commands/FindCommand.java
> +                .add("predicate", cPredicate)
This `toString` representation is very undescriptive.

2024-03-31 04:17 UTC, Hibeom0929 commented
> Apart from these minor changes pointed out, overall there appears to be some unnecessary duplication of logic in `NameContainsKeywordPredicate` and `CourseContainsKeywordPredicate`. How does the rest think about the design?

Tbh, they are basically the same. Only the difference is one is Name and one is Course.

2024-03-31 05:28 UTC, E0735389 reviewed
>  they are basically the same. Only the difference is one is Name and one is Course.

That's the point (nevertheless I don't really see a very good way to avoid the duplication of code either). We see what people may say in the forum `https://github.com/nus-cs2103-AY2324S2/forum/issues/619`

2024-03-31 05:28 UTC, E0735389 commented on src/main/java/seedu/address/model/person/CourseContainsKeywordsPredicate.java
> +                .anyMatch(keyword -> StringUtil.containsWordIgnoreCase(person.getCourse().value, keyword));
Thinking about it, this is needlessly redundant as well. Isn't a course code always a single word anyway?

2024-03-31 05:28 UTC, E0735389 commented on src/main/java/seedu/address/logic/commands/FindCommand.java
> +                .add("course predicate", cPredicate)
The point is that the fieldName should be **the name of the field**, according to `ToStringBuilder`'s documentation.

Also that the field name appears to be needlessly obscure as well, but not a big deal.

2024-03-31 05:30 UTC, E0735389 requested changes

2024-03-31 05:30 UTC, E0735389 commented on src/main/java/seedu/address/logic/parser/FindCommandParser.java
> +                               new CourseContainsKeywordsPredicate(Arrays.asList((keywords))));
Redundant parentheses here.

2024-03-31 06:56 UTC, Hibeom0929 commented
> > they are basically the same. Only the difference is one is Name and one is Course.
> 
> That's the point (nevertheless I don't really see a very good way to avoid the duplication of code either). We see what people may say in the forum `https://github.com/nus-cs2103-AY2324S2/forum/issues/619`

Based on the reply in the forum, I think we can have both NameContainsKeywordPredicate and CourseContainsKeywordPredicate because it is clear and easy to be tested.

2024-04-02 06:05 UTC, E0735389 approved these changes

2024-04-02 06:05 UTC, merged